#!/usr/bin/env python3
from __future__ import annotations

import re
from collections import Counter, defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REPORTS = ROOT / "knowledge" / "reports"
INDEX = REPORTS / "INDEX.md"


def parse_frontmatter(path: Path) -> dict[str, str]:
    text = path.read_text(encoding="utf-8", errors="replace")
    if not text.startswith("---\n"):
        return {}
    end = text.find("\n---\n", 4)
    if end == -1:
        return {}
    out: dict[str, str] = {}
    for line in text[4:end].splitlines():
        if ":" not in line:
            continue
        k, v = line.split(":", 1)
        out[k.strip()] = v.strip().strip('"')
    return out


def first_h1(path: Path) -> str:
    for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        if line.startswith("# "):
            return line[2:].strip()
    return path.stem


def inferred_date(name: str) -> str:
    m = re.match(r"^(\d{4}-\d{2}-\d{2})__", name)
    return m.group(1) if m else "unknown"


def main() -> int:
    files = sorted(p for p in REPORTS.glob("*.md") if p.name != "INDEX.md")
    rows: list[dict[str, str]] = []
    for p in files:
        fm = parse_frontmatter(p)
        rows.append(
            {
                "name": p.name,
                "title": fm.get("title") or first_h1(p),
                "date": fm.get("date") or inferred_date(p.name),
                "source": fm.get("source") or "unknown",
                "ingest_from": fm.get("ingest_from") or "unknown",
            }
        )

    total = len(rows)
    src_counts = Counter(r["source"] for r in rows)
    by_date: dict[str, list[dict[str, str]]] = defaultdict(list)
    for r in rows:
        by_date[r["date"]].append(r)

    lines: list[str] = []
    lines.append("# Reports Library Index")
    lines.append("")
    lines.append("_Generated by `tools/gen_reports_index.py`. Do not edit manually._")
    lines.append("")
    lines.append(f"Total reports: {total}")
    lines.append("")
    lines.append("## Source distribution")
    for src, count in sorted(src_counts.items(), key=lambda x: (-x[1], x[0])):
        lines.append(f"- {src}: {count}")

    for dt in sorted(by_date.keys(), reverse=True):
        lines.append("")
        lines.append(f"## {dt}")
        for r in sorted(by_date[dt], key=lambda x: x["name"]):
            lines.append(
                f"- `{r['name']}` — **{r['title']}**  \n"
                f"  Source: {r['source']}; Ingested from: `{r['ingest_from']}`"
            )

    INDEX.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    print(f"wrote {INDEX}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
